[package]
name = "einsum-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
katexit = "0.1.2"
nom = "7.1.1"
thiserror = "1.0.37"

[dev-dependencies]
maplit = "1.0.2"
